[package]
name = "gendemo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thursday = { path = "../../thursday" }
minijam = { path = "../../core" }
rand = { version = "0.8" }
